<?php
// MediaLinks - Multimedia Contents Holder Module
// $Id: xoops_version.php,v 1.10 2007/11/25 07:59:40 nobu Exp $

$modversion=array(
    'name'	=> _MI_MEDIALINKS_NAME,
    'version'	=> "1.98",
    'description'=> _MI_MEDIALINKS_DESC,
    'credits'	=> "Nobuhiro Yasutomi",
    'author'	=> "Nobuhiro Yasutomi",
    'help'	=> "help.html",
    'license'	=> "GPL see LICENSE",
    'official'	=> 0,
    'image'	=> "medialinks_slogo.png",
    'dirname'	=> basename(dirname(__FILE__)));

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][] = "medialinks";
$modversion['tables'][] = "medialinks_keys";
$modversion['tables'][] = "medialinks_relation";
$modversion['tables'][] = "medialinks_fields";
$modversion['tables'][] = "medialinks_attach";
$modversion['tables'][] = "medialinks_access";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][]=array('file' => 'medialinks_item.html',
				 'description' => _MI_MEDIALINKS_ITEM_TPL);
$modversion['templates'][]=array('file' => 'medialinks_index.html',
				 'description' => _MI_MEDIALINKS_INDEX_TPL);
$modversion['templates'][]=array('file' => 'medialinks_entry.html',
				 'description' => _MI_MEDIALINKS_ENTRY_TPL);
$modversion['templates'][]=array('file' => 'medialinks_detail.html',
				 'description' => _MI_MEDIALINKS_DETAIL_TPL);
$modversion['templates'][]=array('file' => 'medialinks_list.html',
				 'description' => _MI_MEDIALINKS_LIST_TPL);
$modversion['templates'][]=array('file' => 'medialinks_list_shots.html',
				 'description' => _MI_MEDIALINKS_LISTSHOTS_TPL);
$modversion['templates'][]=array('file' => 'medialinks_operate.html',
				 'description' => _MI_MEDIALINKS_OPERATE_TPL);
$modversion['templates'][]=array('file' => 'medialinks_uploads.html',
				 'description' => _MI_MEDIALINKS_UPLOADS_TPL);

$modversion['templates'][]=array('file' => 'medialinks_rss.xml',
				 'description' => _MI_MEDIALINKS_RSS_TPL);
$modversion['templates'][]=array('file' => 'medialinks_track.asx',
				 'description' => _MI_MEDIALINKS_ASX_TPL);
$modversion['templates'][]=array('file' => 'medialinks_track.qtl',
				 'description' => _MI_MEDIALINKS_QTL_TPL);
// OnInstall - initialize table records
$modversion['onInstall'] = "oninstall.php";

// OnUpdate - upgrade DATABASE 
$modversion['onUpdate'] = "onupdate.php";

// Blocks
$modversion['blocks'][1]=array(
    'file' => "medialinks_block.php",
    'name' => _MI_MEDIALINKS_BLOCK_NEW,
    'description' => _MI_MEDIALINKS_BLOCK_NEW_DESC,
    'show_func' => 'b_medialinks_show',
    'edit_func' => 'b_medialinks_edit',
    'options' => 'ctime|5|32||0',
    'template' => 'medialinks_block.html');

$modversion['blocks'][]= array(
    'file' => "medialinks_block.php",
    'name' => _MI_MEDIALINKS_BLOCK_TOP,
    'description' => _MI_MEDIALINKS_BLOCK_TOP_DESC,
    'show_func' => 'b_medialinks_show',
    'edit_func' => 'b_medialinks_edit',
    'options' => 'hits|5|32||0',
    'template' => 'medialinks_block.html');

$modversion['blocks'][]= array(
    'file' => "medialinks_block.php",
    'name' => _MI_MEDIALINKS_BLOCK_MODIFY,
    'description' => _MI_MEDIALINKS_BLOCK_MODIFY_DESC,
    'show_func' => 'b_medialinks_show',
    'edit_func' => 'b_medialinks_edit',
    'options' => 'mtime|5|32||0',
    'template' => 'medialinks_block.html');

// Menu
$modversion['hasMain'] = 1;

$modversion['sub'][]=
    array('name' => _MI_MEDIALINKS_LIST, 'url' => 'list.php');
$modversion['sub'][]=
    array('name' => _MI_MEDIALINKS_NEW, 'url' => 'entry.php');

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "medialinks_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'detail.php';
$modversion['comments']['itemName'] = 'mid';

// Config
$modversion['hasconfig'] = 1;
$modversion['config'][]=array(
    'name' => 'post_group',
    'title' => '_MI_MEDIALINKS_POSTGRP',
    'description' => '_MI_MEDIALINKS_POSTGRP_DSC',
    'formtype' => 'group_multi',
    'valuetype' => 'array',
    'default' => array(XOOPS_GROUP_USERS));
$modversion['config'][]=array(
    'name' => 'notify_admin',
    'title' => '_MI_MEDIALINKS_NOTIFYAD',
    'description' => '_MI_MEDIALINKS_NOTIFYAD_DC',
    'formtype' => 'yesno',
    'valuetype' => 'int',
    'default' => 1);
$modversion['config'][]=array(
    'name' => 'notify_group',
    'title' => '_MI_MEDIALINKS_NOTIFYGRP',
    'description' => '_MI_MEDIALINKS_NOTIFYGRP_D',
    'formtype' => 'group',
    'valuetype' => 'int',
    'default' => XOOPS_GROUP_ADMIN);
$modversion['config'][]=array(
    'name' => 'max_list',
    'title' => '_MI_MEDIALINKS_MAXLIST',
    'description' => '_MI_MEDIALINKS_MAXLIST_DSC',
    'formtype' => 'text',
    'valuetype' => 'int',
    'default' => 10);
$modversion['config'][]=array(
    'name' => 'list_style',
    'title' => '_MI_MEDIALINKS_LISTSTYLE',
    'description' => '_MI_MEDIALINKS_LISTSTYLE_DSC',
    'formtype' => 'select',
    'valuetype' => 'int',
    'options'=>array(_MI_MEDIALINKS_STYLE_SHORT=>0,
		     _MI_MEDIALINKS_STYLE_VERB=>1,
		     _MI_MEDIALINKS_STYLE_SHOTS=>2),
    'default' => 2);
$modversion['config'][]=array(
    'name' => 'max_rows',
    'title' => '_MI_MEDIALINKS_MAXROWS',
    'description' => '_MI_MEDIALINKS_MAXROWS_DSC',
    'formtype' => 'text',
    'valuetype' => 'int',
    'default' => 50);
$modversion['config'][]=array(
    'name' => 'postauth',
    'title' => '_MI_MEDIALINKS_POSTAUTH',
    'description' => '_MI_MEDIALINKS_POSTAUTH_DC',
    'formtype' => 'yesno',
    'valuetype' => 'int',
    'default' => 0);
$modversion['config'][]=array(
    'name' => 'user_acl',
    'title' => '_MI_MEDIALINKS_USERACL',
    'description' => '_MI_MEDIALINKS_USERACL_DSC',
    'formtype' => 'yesno',
    'valuetype' => 'int',
    'default' => 0);
$modversion['config'][]=array(
    'name' => 'user_upload',
    'title' => '_MI_MEDIALINKS_USERUPLOAD',
    'description' => '_MI_MEDIALINKS_USERUP_DSC',
    'formtype' => 'group_multi',
    'valuetype' => 'array',
    'default' => array(XOOPS_GROUP_USERS));
$modversion['config'][]=array(
    'name' => 'upload_path',
    'title' => '_MI_MEDIALINKS_UPLOADPATH',
    'description' => '_MI_MEDIALINKS_UPPATH_DSC',
    'formtype' => 'text',
    'valuetype' => 'string',
    'default' => $modversion['dirname']);
$modversion['config'][]=array(
    'name' => 'upload_ext',
    'title' => '_MI_MEDIALINKS_UPLOADEXT',
    'description' => '_MI_MEDIALINKS_UPEXT_DSC',
    'formtype' => 'text',
    'valuetype' => 'string',
    'default' => 'gif|jpg|png|avi|mov|wmv|mp4|flv|doc|xls|ods|odt|pdf');
$modversion['config'][]=array(
    'name' => 'shotopts',
    'title' => '_MI_MEDIALINKS_SHOTOPTS',
    'description' => '_MI_MEDIALINKS_SOPTS_DC',
    'formtype' => 'text',
    'valuetype' => 'string',
    'default' => '-ss 5');
$modversion['config'][]=array(
    'name' => 'd3forumid',
    'title' => '_MI_MEDIALINKS_D3FORUMID',
    'description' => '_MI_MEDIALINKS_D3ID_DESC',
    'formtype' => 'text',
    'valuetype' => 'string',
    'default' => '');

// Notification

$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'medialinks_notify_iteminfo';

$modversion['notification']['category'][1] =
    array('name' => 'global',
	  'title' => _MI_MEDIALINKS_GLOBAL_NOTIFY,
	  'description' => _MI_MEDIALINKS_GLOBAL_NOTIFY_DESC,
	  //'item_name' => 'keyid',
	  'subscribe_from' => array('index.php','detail.php','list.php')
	);
$modversion['notification']['category'][] =
    array('name' => 'keyword',
	  'title' => _MI_MEDIALINKS_KEYWORD_NOTIFY,
	  'description' => _MI_MEDIALINKS_KEYWORD_NOTIFY_DESC,
	  'item_name' => 'keyid',
	  'subscribe_from' => array('index.php','detail.php', 'list.php')
	);
$modversion['notification']['category'][] =
    array('name' => 'content',
	  'title' => _MI_MEDIALINKS_CONTENT_NOTIFY,
	  'description' => _MI_MEDIALINKS_CONTENT_NOTIFY_DESC,
	  'item_name' => 'mid',
	  'subscribe_from' => 'detail.php'
	);
$modversion['notification']['event'][1]=
    array('name' => 'new',
	  'category' => 'global',
	  'title' => _MI_MEDIALINKS_NEWPOST_NOTIFY,
	  'caption' => _MI_MEDIALINKS_NEWPOST_NOTIFY_CAP,
	  'description' => '',
	  'mail_template' => 'newpost',
	  'mail_subject' => _MI_MEDIALINKS_NEWPOST_SUBJECT);
$modversion['notification']['event'][]=
    array('name' => 'new',
	  'category' => 'keyword',
	  'title' => _MI_MEDIALINKS_NEWPOST_NOTIFY,
	  'caption' => _MI_MEDIALINKS_NEWPOST_NOTIFY_CAP,
	  'description' => '',
	  'mail_template' => 'newpost',
	  'mail_subject' => _MI_MEDIALINKS_NEWPOST_SUBJECT);
?>